### ISSUE TITLE
Media player only showing information when Ziggogo.tv web application is running

### ISSUE THREAD

**Issue by Sholofly** [Sholofly/ZiggoNext#10]
When a media player is starting up  it isn't able to show the now playing information when the webapp on ziggogo.tv isn't running.
after triggering a change using the remote on zigogo.tv, it works.
I'm looking for someone who kan reverse engineer the ziggogo.tv app.

**Comment by Sholofly** [comment]
@PostSven, please help to find a reproduction flow where this bug occurs every time..

**Comment by PostSven** [comment]
@shortwood 
1. restart HA
2. notice that the cover image is not updated
3. go to ziggo phone or web app
4. connect and switch channels
5. all seems OK.

same thing hapens over and over every time you restart HA.

**Comment by Sholofly** [comment]
@PostSven As soon as we close the web app, the data flow is stopped. Only the state is coming through...

**Comment by PostSven** [comment]
@Sholofly this component seems to work: https://github.com/IIStevowII/ziggo-mediabox-next

**Comment by Sholofly** [comment]
Did you try it? It doesn't give me any channel details. Only the selected channel name as i selected myself. It doesn't retrieve channel info after changing it woth remote or web app...

**Comment by PostSven** [comment]
it gives all the details, but only when using HA (not with webapp or remote..) But it looks like the connection from ha to the box is more stable

**Comment by Sholofly** [comment]
I understand, but the component is out of sync when you use the remote...
And it's not synced at startup, is it? I could add the functionality that
it uses the channel name on switching channel. But that's not the way I
would like it to work. In that case HA decides what is playing instead of
the box... I rather like the box showing no information instead wrong
information..

Op zo 19 jan. 2020 17:11 schreef PostSven <notifications@github.com>:

**Comment by PostSven** [comment]
I understand, that would be the ideal way!

**Comment by nelbs** [comment]
I dont know if this is going to help you but yesterday @basst85 added the same feature to his repository https://github.com/basst85/NextRemoteJs/commits/master

**Comment by basst85** [comment]
> I dont know if this is going to help you but yesterday @basst85 added the same feature to his repository https://github.com/basst85/NextRemoteJs/commits/master

Hi! I see this repository for the first time, thanks to your mention 🙂 This project is looking good, gonna try it soon 

And Hopefully my commit from yesterday helps solving this issue 👍🏻

**Comment by Sholofly** [comment]
It looks like it is fixed! Thanks to @basst85 .... I had to refactor the code completely. Hioes it works out for you all!
