### ISSUE TITLE
feature request: add source state

### ISSUE THREAD

**Issue by PostSven** [Sholofly/ZiggoNext#11]
I would also like to make some automations based on the selected source (for instance all lights turn green when watching fox sports), but i believe that the source is not reported back as a state, is this something that is possible?

**Comment by Sholofly** [comment]
The new version has added a channel sensor. Alert: It contains a breaking change. You'll have to update your config... Check the readme in the details.

**Comment by PostSven** [comment]
getting a lot of errors, also the state is not updating.

the source state in the media player is sometimes updating, but is also getting stuck on the channel that is set via the ziggogo.tv app.

Also i am experiencing the same behaviour as with the image not updating, the state of source only updates after a refresh via the webapp, but when the box is turned off/on the same issue appears again.

Log Details (ERROR)
Fri Jan 17 2020 23:43:40 GMT+0100 (Central European Standard Time)
Update for sensor.stb_arris_uhd_channel fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 461, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/ziggonext/sensor.py", line 42, in update
    self._box = api.settopBoxes[boxId]
NameError: name 'api' is not defined

**Comment by Sholofly** [comment]
Sure you updated to the latest version? There was a wrong version live for
a few minutes last night. It looks like you did update in that short time
window. Sorry for the inconvenience.

Op vr 17 jan. 2020 23:46 schreef PostSven <notifications@github.com>:

**Comment by Sholofly** [comment]
Oh, and the bug with not updating at startup is in issue #10 .

**Comment by PostSven** [comment]
That looks better! i was to quick!

only issue now is that the source is not updating when switching channels, it stays on the 1st one you set.

**Comment by Sholofly** [comment]
It does change, but it takes a while. Sensors are not updating that
quickly...

Op za 18 jan. 2020 om 11:09 schreef PostSven <notifications@github.com>:

**Comment by PostSven** [comment]
It only updates for the first one, if you switch channel it will not update it.

**Comment by Sholofly** [comment]
Are there errors in the log?

Op za 18 jan. 2020 13:42 schreef PostSven <notifications@github.com>:

**Comment by PostSven** [comment]
No, nothing.

It looks similar to the picture not updating, that also stays with the first channel that is picked.

unfortunatly i am not a big star with code, so i can't be of much help other then testing and reproducing the issues, sorry for that!

**Comment by Sholofly** [comment]
Do you mean that when the picture is notupdating, the sensor isnt updating
too? Or does the sensor not update even when the media player does?  Cause
that makes sense. They rely on the same data source.

Op za 18 jan. 2020 15:09 schreef PostSven <notifications@github.com>:

**Comment by PostSven** [comment]
Correct, when changing the source via HA or via the TV remote, it's not updating the source or picture/channel info.

when changing the source via the ziggo app it is updating.

**Comment by PostSven** [comment]
Update: when having a “connection” in the ziggo app to the next box open everything works like a charm.

When closing the app it reverts to the above behaviour

**Comment by Sholofly** [comment]
Strange,
 I'll dive into it...

Op za 18 jan. 2020 17:16 schreef PostSven <notifications@github.com>:
