### ISSUE TITLE
Feature Request Add Swiss Servers

### ISSUE THREAD

**Issue by netrene** [Sholofly/ZiggoNext#13]
Hi,

as discussed in the Forum it would be greta to add the Swiss Servers to make your component work also with the Swiss version of the ziggo box. Here it is called UPC TV Box.

Here are the Servers to implement:

API_URL_SESSION = "https://web-api-prod-obo.horizon.tv/oesp/v3/CH/eng/web/session"
API_URL_TOKEN = "https://web-api-prod-obo.horizon.tv/oesp/v3/CH/eng/web/tokens/jwt"
DEFAULT_HOST = "obomsg.prod.ch.horizon.tv"

Many thanks in advance

**Comment by Sholofly** [comment]
@netrene I created a branch countrycode where I have fixed this. Please test it for me, since i don't have access to the CH url's. You have to copy the files manually in your custom components, add ```country_code: ch``` to your config & restart.

**Comment by netrene** [comment]
Hi,

first of all thanks for your effort.

I tested it and it is not working. I get the following error:

Protokolldetails ( ERROR )
Sat Jan 18 2020 15:55:06 GMT+0100 (CET)

Error during setup of component ziggonext
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 174, in _async_setup_component
    component.setup, hass, processed_config  # type: ignore
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/ziggonext/__init__.py", line 29, in setup
    api = ZiggoNext(config[DOMAIN][CONF_USERNAME], config[DOMAIN][CONF_PASSWORD],config[DOMAIN][CONF_COUNTRY_CODE])
KeyError: 'ziggonext'

**Comment by netrene** [comment]
Forget what I wrote. Its working. 

I did not see that I have to change the config to:

ziggonext:
  username: !secret ziggo_username
  password: !secret ziggo_password  

I found this information here: https://github.com/Sholofly/ZiggoNext/compare/3546899...444769f

Many many Thanks.

**Comment by Sholofly** [comment]
Hi thank you for testing. I will merge the changes into the main branch so
you can use the custom component in HACS...

Op za 18 jan. 2020 16:09 schreef netrene <notifications@github.com>:
