### ISSUE TITLE
Cannot see media_player and sensor

### ISSUE THREAD

**Issue by khensel17** [Sholofly/ZiggoNext#15]
Hello,
I've been struggeling to get this integration working. I've installed it with HACS and added the configuration. After restarting HA several times I cannot find any entities related to this integration. Is there someone who can tells me where to look or how to debug this?

**Comment by Sholofly** [comment]
it looks like you figured it out?

**Comment by khensel17** [comment]
> it looks like you figured it out?

Yes I did. Thanks for replying anyway
