### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by gerthass** [Sholofly/ZiggoNext#16]
Is it possible with the ziggonext sensor to add a 3rd state: idle/unknown for when the Next is playing youtube of nexflix
Or maybe the attribute ‘content’ which is now always on ‘tvshow’?
(Or another source input when not playing a chanel)

this way I could create an automation when the state/attribute changes from playing music on youtube, or a serie on nexflix back to the normal TV playing I could send an IR signal to the receiver to change to another sound mode :smile:

**Comment by Sholofly** [comment]
Fixed in latest release
