### ISSUE TITLE
Sensor is not updating when playing Replay TV

### ISSUE THREAD

**Issue by silver323** [Sholofly/ZiggoNext#19]
Is it possible that the sensor is being updated when watching back with ReplayTV?

**Comment by Sholofly** [comment]
Hi @silver323 ,

I have a pull request for integrating this component in HA Core. In that PR the sensors are removed and added as attribute to the media player. Until further notice i've stopped the development of this custom integration. If my PR is not merged soon i will add the same functionality to this component.

**Comment by Sholofly** [comment]
@silver323  I've decided to go on with de development of this component. I'll keep you posted!

**Comment by Sholofly** [comment]
@silver323 What shoud the sensor say when playing a recording? The channel of the record?

**Comment by silver323** [comment]
@Sholofly If it's possible to see the channel it's great. Otherwise showing the status ReplayTV.

**Comment by Sholofly** [comment]
Should be solvee when updating to latest version!
