### ISSUE TITLE
Not showing if you listening to radio

### ISSUE THREAD

**Issue by silver323** [Sholofly/ZiggoNext#20]
The media player and the sensor stays on the latest tv program when you switch to the radio. 
So it's not showing when you listening to radio. Is that possible?

**Comment by gerthass** [comment]
This would be a nice one, I can't see when the next is playing the radio app, and not which radio channel. This would be usefull to You could create a script which would instantly start the right radio channel and sound mode

**Comment by Sholofly** [comment]
At the moment i don't know how te retrieve radio information. I'll dive into this requst later.

**Comment by Sholofly** [comment]
The interface does not support it. Therefor i have to close this. I'm sorry!
