### ISSUE TITLE
ZiggoNext as switch in google assistant

### ISSUE THREAD

**Issue by trippinnl** [Sholofly/ZiggoNext#22]
I have exposed the media_player component to google home.

However in the google home app it is listed as switch rather than a media player. Because of that i can only turn it on and off. I'm unable to switch it to another channel or pause the box.

Is it possible to fix this?

**Comment by Men-noemt-m-O** [comment]
I created a script for every channel with the name of the channel and exposed the scripts to Google home. That way I can ask to "turn on RTL 4" or "activate RTL 4" and Google home changes the channel for me, it's working great.

**Comment by Sholofly** [comment]
It is showing as media device now.

**Comment by BRdev** [comment]
It's showing as a media device and when you tap on it, the only thing you can do is turn it on/off. Maybe there's a method to make the HA media-component controlls like play/pause and source available in Google Assistant. 

![Screenshot_20201022-214334_Home](https://user-images.githubusercontent.com/7237925/96922501-3ae7c700-14b0-11eb-8553-4a0c471a0583.jpg)
![Screenshot_20201022-214325_Home](https://user-images.githubusercontent.com/7237925/96922508-3b805d80-14b0-11eb-8df2-01881e28757b.jpg)
