### ISSUE TITLE
[0.110.0b3] MediaPlayerDevice is deprecated, modify ZiggoNextMediaPlayer to extend MediaPlayerEntity

### ISSUE THREAD

**Issue by dynasticorpheus** [Sholofly/ZiggoNext#25]
homeassistant==0.110.0b3 is raising below warning hence thought giving heads up on this

`WARNING (MainThread) [homeassistant.components.media_player] MediaPlayerDevice is deprecated, modify ZiggoNextMediaPlayer to extend MediaPlayerEntity
`

**Comment by ping-localhost** [comment]
This issue seems to be resolved with the latest release (v0.1.8). Thanks @Sholofly.

**Comment by dynasticorpheus** [comment]
Thanks @Sholofly
