### ISSUE TITLE
Cannot change the sensor-name

### ISSUE THREAD

**Issue by bouwew** [Sholofly/ZiggoNext#31]
When I try to change the sensorname, this message is displayed:
![image](https://user-images.githubusercontent.com/11290930/84471688-2126af80-ac86-11ea-8f6b-adc596c5385e.png)

Core: 0.111.1

**Comment by Sholofly** [comment]
I'll take a look at it soon but I'm thinking about deprecating the sensor. There's an attribute with the same information. I suggest you create a template sensor: [Home Assistant Template Sensor](https://www.home-assistant.io/integrations/template/)

**Comment by bouwew** [comment]
Yes, I noticed that this is your plan, from the code in your Core PR. I don't mind you following your plan, I would like to suggest that you first create your custom_component as you are planning to integrate it into Core. And have the community test it for you. Once it is working bug-free as a custom_component, then try getting it into HA.

When trying that, you will get a lot of feedback on the coding, I/we've been through that process twice (Plugwise) so better to have working code otherwise you are bug-fixing and adapting code-style at the same time :)

**Comment by Sholofly** [comment]
Hi Bouwe, Thanks for your feedback! That's exactlyt how i've planned. The last few months i wasn't able to follow up on my integration in core. As result it's marked stale and I decided to leave it for now and do exactly what you suggest, develop my custom_component a bit more. Part of that process  is **deprecating only the sensor part** and focus on the media_player and the python package behind it. The channel is available in the attributes.

Although I'm a developer, I've no experience with python. It sounds like you have. Are you willing to take a look at the python package and review it? It would be of great help to me.

**Comment by bouwew** [comment]
I think your python-experience-level is similar to mine, I've started coding about 6 months ago. But I have a "partner in crime" that has more experience, learned a lot from him. Let me know when you'd want some reviewing done, I'll ask him (@CoMPaTech) if he can help out too.

On the other hand, once you go the Core-route, there will be heavy reviewing going on. But more focused on the code to integrate, less on the library.

**Comment by Sholofly** [comment]
Hey, didn't say I wouldn't fix the request :)

**Comment by Sholofly** [comment]
@bouwew Can you update your component and check if it works for you?

**Comment by bouwew** [comment]
Sorry, not now, maybe later today or tomorrow..

**Comment by bouwew** [comment]
Yes, it's working, thanks!!

**Comment by CoMPaTech** [comment]
If you need any comments or feedback just ping me :)
