### ISSUE TITLE
Component stopped working

### ISSUE THREAD

**Issue by netrene** [Sholofly/ZiggoNext#36]
Hi,

since today update to version 0.1.16 the component is not working anymore. I have the following error:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 191, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/ziggonext/__init__.py", line 30, in setup
    api.initialize(_LOGGER)
  File "/usr/local/lib/python3.8/site-packages/ziggonext/ziggonext.py", line 159, in initialize
    self._register_settop_boxes()
  File "/usr/local/lib/python3.8/site-packages/ziggonext/ziggonext.py", line 83, in _register_settop_boxes
    jsonResult = self._do_api_call(self.session, self._api_url_settop_boxes)
  File "/usr/local/lib/python3.8/site-packages/ziggonext/ziggonext.py", line 132, in _do_api_call
    raise ZiggoNextConnectionError("API call failed: " + str(response.status_code))
ziggonext.exceptions.ZiggoNextConnectionError: API call failed: 403

When I reinstall V 0.1.13 and reboot everything is working fine again.

HA 0.114.4
Location: Switzerland

**Comment by Sholofly** [comment]
Please find out what's the personalization URL for your country, using the player in your browser..

**Comment by netrene** [comment]
Hi,

can you please be a bit more specific.

I´m using country code CH and it is still working with 0.1.13. So I don´t think that there is a problem with the Server URL´s unless you changed them?

René

**Comment by Sholofly** [comment]
Yeah of course,
You can play tv from your provider in your browser right?

When you open the browser en are logged in check in the developer toolbar (chrome => F12) under the network tab if you can find an URL that ends with: '/personalization-service/v1/customer/<here your id>' Please send me the complete URL but WITHOUT the id.

**Comment by netrene** [comment]
https://prod.spark.upctv.ch/deu/web/personalization-service/v1/customer/

**Comment by Sholofly** [comment]
Thanks!

Op do 27 aug. 2020 18:04 schreef netrene <notifications@github.com>:

**Comment by netrene** [comment]
Tested with 0.1.17 --> working fine now

Thx for the fast fix.
