### ISSUE TITLE
Feature Request: detect when the Mediabox is OFF or ON, update HA Core via local push.

### ISSUE THREAD

**Issue by bouwew** [Sholofly/ZiggoNext#39]
Hi Rudy, I was thinking, could the Integration benefit from being “local push”? I was thinking, when being based on push, the Mediabox would not need to be in the high energy mode, the Integration could scan regularly until it finds the Mediabox to be powered on?

**Comment by Sholofly** [comment]
Hi Bouwe,

Did you realize that when the box is in energy saving mode, you aren't able to turn the box on with the integration?

**Comment by bouwew** [comment]
Yes, I realize that. I never use the integration to turn the box on or off. This is always done via the Harmony Hub remote control, which also controls the TV and the surround receiver.

I realize I could do all this from HA Core but I prefer to keep using the Hub as it allows me to turn the box off, so it does not consume too much power when it's off, which is at least 70-80% of the time. Also, in the high-energy-mode the box is too noise for my taste.

**Comment by bouwew** [comment]
Just tried whether this works, with version 0.4.6.
This seems to work now: the component reports the box as unavailable until I switch it on. Then the mediaplayer-card shows the box as active, displaying the program info etc. When I switch it back to off, that is also quickly displayed on the mediaplayer-card.

Nice job, thanks!!
