### ISSUE TITLE
Status updates not coming thru in PyPi branch

### ISSUE THREAD

**Issue by Sholofly** [Sholofly/ZiggoNext#4]
@shortwood  I've created a pypi package to control the settop boxes but one way or another, i'm not receiving status updates anymore. The source for the package is in the python repo. The custom-component that uses this package for HA is a branch from this one. 

I did all i can do to compare the master and the pypi branch in HA but although it looks kinda the same, the master (without pypi package) works but the PyPi banch doesn't... I can't figure out why, Would you mind to take a look? Four eyes see more than two.

My goal with moving to a package is to get the mediabox next integration into home assistant instead of a custom component. Using packages is a requirement for that.

**Comment by dynasticorpheus** [comment]
@Sholofly  Please note paho-mqtt version is bumped to 1.5.0 (paho-mqtt==1.5.0)

**Comment by Sholofly** [comment]
@dynasticorpheus thanks, but the package already uses that version..

**Comment by Sholofly** [comment]
Looks like it's fixed.
