### ISSUE TITLE
Sensors reacts slow

### ISSUE THREAD

**Issue by mvanrijnen** [Sholofly/ZiggoNext#48]
When changing channel, the Next Card displays the choosen new channel immediatly, but it takes a few seconds before the sensor changes ? (tested it with putting the ZIggoNext  card, and an entity card with the sensor.ziggnonext_channel on the frontend

**Comment by Polderdijk** [comment]
You can fix this with template sensors:

- platform: template
  sensors:
    your_name:
      friendly_name: Your friendly name
      value_template: "{{ state_attr('media_player.ziggo', 'channel (or any other attribute)' }}"
      icon_template: mdi:television

**Comment by Sholofly** [comment]
I'm planning to deprecate the channel sensor, because @Polderdijk is right. You can create template sensors out of the attributes.
