### ISSUE TITLE
0.5.0 requires "ok" when changing channel

### ISSUE THREAD

**Issue by Steefph** [Sholofly/ZiggoNext#50]
When trying to change the channel using the service a pop-up is shown on the TV asking to press ok. 

I call the service using:
entity_id: media_player.mediabox
media_content_id: 1
media_content_type: channel

Am I doing something wrong or did Ziggo change something?

**Comment by Sholofly** [comment]
It's a change in the software. I'll dive into this.

**Comment by Polderdijk** [comment]
I found a solution. When you change a channel via a script, i check attribute play_mode. When its reviewbuffer, I turn off the Next. Wait 2 seconds and turn it on. Then change to the new channel.

Maybe we can overcome this when we can send a OK button press via a script when its in reviewbuffer mode?

**Comment by Sholofly** [comment]
@Steefph Can you confirm this issue still exists. I am not able to reproduce the issue.

**Comment by Steefph** [comment]
@Sholofly sorry for the are reply, yes it works perfect now thanks!
