### ISSUE TITLE
Media player not showing up

### ISSUE THREAD

**Issue by GeertvanHorrik** [Sholofly/ZiggoNext#60]
I've enabled this yesterday, but I cannot see the media player.

I tried:

1. Making sure to login to ziggogo.tv => all visible and I can see my mediabox
2. Enabled debug logging. I can see large json data (including my personal info) being returned, so username / pwd seems to work correctly. 

I could not find any mediabox related info in the json, mostly person info, entitlements, etc.

Any idea why it's not showing the horizon box (with latest update)?

Than you.

**Comment by GeertvanHorrik** [comment]
Additional info that might be useful: I can't rename the mediabox on my ziggogo.tv account. Could it be that the new firmware is not yet supported?

**Comment by Sholofly** [comment]
Hi @GeertvanHorrik, this component only supports the ziggo next box, not the horizon boxes. I'm sorry.
