### ISSUE TITLE
Stopped working with 403 error

### ISSUE THREAD

**Issue by Martinvdm** [Sholofly/ZiggoNext#62]
After a long period this integration stopped working.
Error:
Api call resultcode was 403. Refreshing token en trying again...

Username, password is not changed and has worked before. Just updated the component.

**Comment by Martinvdm** [comment]
Any news on this? for whats is worth this is my url:

https://prod.spark.ziggogo.tv/nld/web/personalization-service/v1/customer/

**Comment by Sholofly** [comment]
Hi Martin,,

Sorry for the slow response. Please update your component. Should work, but please keep an eye on the logs!

**Comment by davidvf** [comment]
I have similar behaviour after upgrading to latest version..

I am using the `be-nl` implementation
```
custom_components/ziggonext/__init__.py:30
First occurred: 1:46:07 PM (1 occurrences)
Last logged: 1:46:07 PM

Error during setup of component ziggonext
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ziggonext/ziggonext.py", line 132, in get_oauth_session
    raise ZiggoNextAuthenticationError("Unable to login, wrong credentials")
ziggonext.exceptions.ZiggoNextAuthenticationError: Unable to login, wrong credentials

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/ziggonext/__init__.py", line 30, in setup
    api.connect(_LOGGER)
  File "/usr/local/lib/python3.8/site-packages/ziggonext/ziggonext.py", line 255, in connect
    self.get_session_and_token()
  File "/usr/local/lib/python3.8/site-packages/ziggonext/ziggonext.py", line 59, in get_session_and_token
    self.get_session()
  File "/usr/local/lib/python3.8/site-packages/ziggonext/ziggonext.py", line 65, in get_session
    self.get_oauth_session()
  File "/usr/local/lib/python3.8/site-packages/ziggonext/ziggonext.py", line 171, in get_oauth_session
    raise ZiggoNextConnectionError("Unknown connection failure: " + str(e))
ziggonext.exceptions.ZiggoNextConnectionError: Unknown connection failure: Unable to login, wrong credentials
```

**Comment by Sholofly** [comment]
Hi @davidvf,

There is an issue in the latest version due to merging the Belgian and the British version. Please downgrade your version to get it back up again. I'll let you know when it's solved. My apologies for any inconvenience.

**Comment by Sholofly** [comment]
@michael-geerts would you to investigate this with me? I am the one that broke the component, bit even when I compare it with a working version I can't find what I am doing wrong. Since I can't test it from NL it's hard for me to find the issue. Maybe I can explain to you what I did that broke it?

**Comment by geertsmichael** [comment]
Which is the working version and when did it broke?

**Comment by davidvf** [comment]
In my case v0.8.0 broke the `be-nl` support. Before that i had `v0.7.10` running without any issue.

**Comment by geertsmichael** [comment]
So that means this commit?
https://github.com/Sholofly/ziggonext-python/pull/30/commits/8aa01768d520e3242fb74df75c84ccec1ae56203

**Comment by Sholofly** [comment]
Yeah, it's that commit. I've added GB support, also oAuth. There are minor differences so I merged the function to create a session. Even when I copy the function from the old version. It doesn't work.

**Comment by Sholofly** [comment]
I've managed to fix it. Belgian version should work now after update.

**Comment by Sholofly** [comment]
@Martinvdm  Please enable the debug logging for this component and try again! I did some stability updates.

**Comment by geertsmichael** [comment]
I did test this and it works again for me (BE-nl).
Thanks (and apologies I couldn't help fixing it, too busy work schedule)

**Comment by Sholofly** [comment]
No problem. Thanks for testing...

Op vr 2 apr. 2021 19:05 schreef Michaël ***@***.***>:

**Comment by Sholofly** [comment]
Looks like this issue is fixed.
