### ISSUE TITLE
UK Virgin Media Integration - Virgin TV 360

### ISSUE THREAD

**Issue by craigmcgowan** [Sholofly/ZiggoNext#63]
I believe the new Virgin Media TV 360 boxes which started shipping in November are using the same integration.

URLs to use are https://prod.oesp.virginmedia.com/oesp/v3/CH/eng/web/session

Would be appreciated if this could be added. I'm more than happy to test and feedback then as these boxes are being shipped with all new VM accounts now

Thank you very much.

**Comment by Sholofly** [comment]
I will need another URL to try to make it work. I'll contact you in a few days ok?

**Comment by craigmcgowan** [comment]
Yes of course, just let me know what you require.

Thank you

**Comment by Sholofly** [comment]
Please help me with the following:

I need a URL than starts with something in the following format:
https://prod.spark.ziggogo.tv/nld/web/personalization-service/v1/
Key here is de .spark part and the personalization-service part, the other parts can look slightly different.

To obtain it, please login to the web environment using chrome and press F12
Look for above URL and send it to me in a private message or email.

**Comment by craigmcgowan** [comment]
Just sent you an email with it on.
Thank you very much.

**Comment by Sholofly** [comment]
@craigmcgowan I'm working on it but the login process is different than other providers. It's very difficult to get into it when not being able to login. Are you able to communicate via Discord? You can contact me via Sholofly#4951.

**Comment by Sholofly** [comment]
Added the GB support!
