### ISSUE TITLE
TV channel error

### ISSUE THREAD

**Issue by sven41** [Sholofly/ZiggoNext#73]
TV channel 14 Ziggo sport does not provide the information available

**Comment by sven41** [comment]
Logger: ziggonext.ziggonextbox
Source: /usr/local/lib/python3.8/site-packages/ziggonext/ziggonextbox.py:214
First occurred: 21:04:23 (1 occurrences)
Last logged: 21:04:23
Couldn't set channel. Channel info set to unknown...

**Comment by Sholofly** [comment]
Hi @sven41 Can you confirm that this is temporary? I use that channel often and sometimes there's an issue with the data delivered. Afterwards it will correct itself.

**Comment by sven41** [comment]
> Hi @sven41 Can you confirm that this is temporary? I use that channel often and sometimes there's an issue with the data delivered. Afterwards it will correct itself.

Hi Sholofly, sender 14 ziggo sport always get no information available. The another senders works correctly but 14 always get this.

**Comment by Sholofly** [comment]
Please  update to the latest version. I added some stability improvements. I can't reproduce this behavior. Are you able to enable logging so i can see what's ging on?

**Comment by sven41** [comment]
top I'm going to see if this solves the problem. How can I turn on the log? haha

**Comment by Sholofly** [comment]
@sven41 Dit you experience any issues?

for logging add:

```yaml
logger:
  default: info
  logs:
    custom_components.ziggonext: warning
```

To your config!

**Comment by sven41** [comment]
i add the logging to my config. 14 Ziggo sport don't show the good info...

**Comment by Sholofly** [comment]
Yeah you mentioned that before, but i have the Zoggo sports Channels as well and i don't experience the same troubles, you have, so I am curious about the difference :). BTW i made a mistake in previous message, you should change the component log level to debug! Can you sare the complete logs when you change to channel 14?

**Comment by Sholofly** [comment]
@sven41 Still facing issues?

**Comment by sven41** [comment]
Problem still facing i add the config you tell me. But where i can see the info of the log?

**Comment by Sholofly** [comment]
@sven41 Sorry for the delay, the additional log should be visible in your home assistant log file

**Comment by sven41** [comment]
2021-08-22 20:52:05 WARNING (Thread-3) [ziggonext.ziggonextbox] Couldn't set channel. Channel info set to unknown...

**Comment by Sholofly** [comment]
Hi @sven41. This repo is not longer supported. Please install the new component in HACs (Please mind the extra installation step)
https://github.com/Sholofly/arrisdcx960/
