### ISSUE TITLE
Customise channel names. Or change phonetics of a channel.

### ISSUE THREAD

**Issue by JBakers** [Sholofly/ZiggoNext#79]
I changed some settings and now the Ziggo Next box is fully accessible through Google.
Although this works fine, is it possible to change channel names? Or give them custom names?

For example, when I want to change to the “MTV 80s” channel. I have to pronounce it exactly as that in Dutch (as I’m obviously am Dutch).
So for MTV 80s, I need to say: “Hey Google, zet Ziggo op MTV tachtig S”
For NL 1 I’m supposed to say “NPO één HD”

It would be a lot simpler to give them a custom name based on our pronunciation, like “Nederland 1” or “MTV Eighties”.

**Comment by Sholofly** [comment]
@JBakers Please update the component and update your config according to de readme and you are good to go. It doesn't count for the MTV channel though...
