### ISSUE TITLE
State of the mediabox

### ISSUE THREAD

**Issue by MisterMeJ** [Sholofly/ZiggoNext#82]
Is it possible to get extra states from the mediabox?
Now it's only possible to get the 'off" or 'playing' state, but it would be nice if we can get also the 'pause' state.

Possible to archive this?

Thanks in advance

**Comment by Sholofly** [comment]
The media player is paused hen you pause your recording or live tv isn't it?

**Comment by MisterMeJ** [comment]
Apologize, forgotten to mention it's for Netflix and Videoland!

**Comment by Sholofly** [comment]
Unfortunately that's not possible. They are apps and do not transmit the playing state...
