### ISSUE TITLE
Homekit problem

### ISSUE THREAD

**Issue by AndyVRD** [Sholofly/ZiggoNext#86]
First of all, thanks for this great integration. Just noticed if i add the media_player.telenettvbox to the HA Homekit integration makes all other homekit devices unresponsive. Any change you can look into this issue? Thx!

**Comment by Sholofly** [comment]
I am not familiar with the homekit integration. What is the use of that?

**Comment by AndyVRD** [comment]
> I am not familiar with the homekit integration. What is the use of that?

HomeKit is Apple’s IoT platform. So you can add devices to the Home app and to interact with.

**Comment by Sholofly** [comment]
@AndyVRD Ive created a new component: https://github.com/Sholofly/arrisdcx960/ please install that one instead of this one. (mind the extra installation step)
